apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: wordpress
    tier: frontend
  name: wordpress
  namespace: wordpress
spec:
  ports:
  - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
